# Generated by Django 3.2.6 on 2021-10-05 10:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20211005_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 10, 24, 25, 302495, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 10, 24, 25, 302520, tzinfo=utc)),
        ),
    ]
