# Generated by Django 3.2.6 on 2021-10-05 14:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20211005_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 14, 9, 18, 344277, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 14, 9, 18, 344306, tzinfo=utc)),
        ),
    ]
