# Generated by Django 3.2.6 on 2021-10-06 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20211005_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 12, 20, 40, 654058, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 12, 20, 40, 654104, tzinfo=utc)),
        ),
    ]
